export const FETCH_WORKSTATIONS_START = 'FETCH_WORKSTATIONS_START';
export const FETCH_WORKSTATIONS_END = 'FETCH_WORKSTATIONS_END';
export const BOOK_WORKSTATION = 'BOOK_WORKSTATION';
export const SET_DATE = 'SET_DATE';